### ISSUE TITLE
baramFlow.main errors when I run it

### ISSUE THREAD

**Issue by PizzaRules668** [nextfoam/baram#59]
**Describe the bug** and **To Reproduce**
I am following the [Installation Guide](https://baramcfd.org/docs/installation/) on the website. Once I get to the step where I run ```python -m baramFlow.main``` it throws the following error
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/colin/build/baram/baramFlow/main.py", line 22, in <module>
    from baramFlow.app import app
  File "/home/colin/build/baram/baramFlow/app.py", line 14, in <module>
    from baramFlow.coredb.region_db import RegionDB
  File "/home/colin/build/baram/baramFlow/coredb/region_db.py", line 5, in <module>
    from baramFlow.coredb.material_db import MaterialDB, Phase
  File "/home/colin/build/baram/baramFlow/coredb/material_db.py", line 20, in <module>
    class Specification(Flag):
  File "/usr/lib/python3.11/enum.py", line 566, in __new__
    raise exc
  File "/usr/lib/python3.11/enum.py", line 279, in __set_name__
    enum_class._flag_mask_ |= value
TypeError: unsupported operand type(s) for |=: 'int' and 'str'
```

**Expected behavior**
It should not throw an error

**Desktop (please complete the following information):**
 - OS: Manjaro Linux

**Comment by kdg5424** [comment]
Hi @PizzaRules668 This is Donggyu.
First of all, thank you for your interest in BARAM.

Actually, BARAM doesn't support the Arch Linux like Manjaro Linux, Endeavour Linux.
But there is a way to install and run BARAM on Manjaro Linux.
We recommend you to install with Apptainer.
You can follow on this page.

https://baramcfd.org/docs/installationApptainer/

After following this page if you have the same problem again, please contact to us again.

**Comment by jiban** [comment]
Hi, @PizzaRules668.
Thank you for the report.
The exception *Traceback* shows crucial information for a bug.
I will fix it in next release.
By the way, it may happen with Python 3.11 and is ok with Python 3.9.
Could you try running BARAM with Python 3.9?
